[theme]
primaryColor = "#4CAF50"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#000000"
font = "sans serif"

[server]
headless = true

[client]
showSidebarNavigation = true
